[build]
  command = "cd backend && npm install"
  functions = "backend"
  publish = "backend"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/start/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/start/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/start/:splat"
  status = 200