apiVersion: v1
kind: Namespace
metadata:
  name: squdy-production
  labels:
    name: squdy-production
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: squdy-resource-quota
  namespace: squdy-production
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: squdy-limit-range
  namespace: squdy-production
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container