name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        cd backend
        railway login --token $RAILWAY_TOKEN
        railway up --detach
        
    - name: Set Environment Variables
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        cd backend
        railway variables set MONGODB_URI="$MONGODB_URI"
        railway variables set NODE_ENV="production"
        railway variables set PORT="3001"