name: Deploy to Production / notify

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify (noop)
        run: echo "Notification placeholder; configure Slack/Discord webhook via secrets to enable."


